In [11]:
import numpy as np

## QUESTION 1

In [12]:
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [13]:
array_list

array([1, 2, 3, 4, 5])

In [14]:
type(list_)

list

In [15]:
type(array_list)

numpy.ndarray

In [16]:
list_

[1, 2, 3, 4, 5]

In [17]:
for i in list_:
    print(type(i))
    

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [18]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## QUESTION 3

In [21]:
array_lists = np.array(object = list_, dtype = int)

In [26]:
for i in array_lists:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


## QUESTION 4

In [28]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_list


[[1, 2, 3], [4, 5, 6]]

In [29]:
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.shape(num_array)

(2, 3)

In [31]:
np.size(num_array)

6

## QUESTION 5

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## QUESTION 6

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])